clc;clear all;close all;
A=readmatrix('MAF_NULL.csv');B=readmatrix('MAF_Lo.csv');
C=readmatrix('PCA_NULL.csv');D=readmatrix('PCA_Lo.csv');
tiledlayout(2,2,'TileSpacing','compact','Padding','tight');
nexttile;
bar(A(:,1),A(:,3),'ShowBaseLine','off','EdgeColor','k','LineWidth',1,'BarWidth',0.01);
xlim([0 910]);ylim([-0.5 0.7]);
xticks([0 300 600 910]);xticklabels({});
ylabel('MAF Residual');
title('Gaussian smoothing');
set(gca,'Linewidth',1.5,'Fontweight', 'bold','Fontsize',11,'tickdir','out');
ax=gca;ax.XAxis.Color='k';ax.YAxis.Color='k';
nexttile;
bar(B(:,1),B(:,3),'ShowBaseLine','off','EdgeColor','k','LineWidth',1,'BarWidth',0.01);
xlim([0 910]);
xticks([0 300 600 910]);xticklabels({});
ylabel('MAF Residual');
title('Loess smoothing');
set(gca,'Linewidth',1.5,'Fontweight', 'bold','Fontsize',11,'tickdir','out');
ax=gca;ax.XAxis.Color='k';ax.YAxis.Color='k';
nexttile;
bar(C(:,1),C(:,3),'ShowBaseLine','off','EdgeColor','k','LineWidth',1,'BarWidth',0.01);
xlim([0 910]);
xticks([0 300 600 910]);xticklabels({'0', '3', '6', '9.1'});
ylabel('PCA Residual');
set(gca,'Linewidth',1.5,'Fontweight', 'bold','Fontsize',11,'tickdir','out');
ax=gca;ax.XAxis.Color='k';ax.YAxis.Color='k';
xlabel('Time');
nexttile;
bar(D(:,1),D(:,3),'ShowBaseLine','off','EdgeColor','k','LineWidth',1,'BarWidth',0.01);
xlim([0 910]);
xticks([0 300 600 910]);xticklabels({'0', '3', '6', '9.1'});
ylabel('PCA Residual');
set(gca,'Linewidth',1.5,'Fontweight', 'bold','Fontsize',11,'tickdir','out');
ax=gca;ax.XAxis.Color='k';ax.YAxis.Color='k';
xlabel('Time');